// Generated by CoffeeScript 1.4.0

define(["jquery"], function($) {
  var loadingScreenView;
  return loadingScreenView = (function() {

    function loadingScreenView(divId) {
      this.divId = divId;
    }

    loadingScreenView.prototype.show = function() {
      return $(this.divId).show();
    };

    loadingScreenView.prototype.hide = function() {
      return $(this.divId).hide();
    };

    return loadingScreenView;

  })();
});
