// Generated by CoffeeScript 1.4.0

define(["jquery"], function($) {
  var baseController;
  return baseController = (function() {

    function baseController() {
      console.log("loading Controller");
    }

    baseController.prototype.load = function() {
      console.log("common load ");
      return this.view.show();
    };

    baseController.prototype.unload = function() {
      console.log("common unload");
      return this.view.hide();
    };

    baseController.prototype.setView = function(view) {
      this.view = view;
      return console.log("set view");
    };

    return baseController;

  })();
});
