// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["jquery", "application/controllers/baseController"], function($, baseController) {
  var loadingController;
  return loadingController = (function(_super) {

    __extends(loadingController, _super);

    function loadingController() {
      return loadingController.__super__.constructor.apply(this, arguments);
    }

    loadingController.prototype.load = function() {
      console.log("load loading");
      return loadingController.__super__.load.call(this);
    };

    return loadingController;

  })(baseController);
});
