// Generated by CoffeeScript 1.4.0

define(["jquery"], function($) {
  var loadingController;
  return loadingController = (function() {

    function loadingController() {
      console.log("loading Controller");
    }

    loadingController.prototype.load = function() {
      console.log("load loading");
      return this.view.show();
    };

    loadingController.prototype.unload = function() {
      console.log("unload loading");
      return this.view.hide();
    };

    loadingController.prototype.setView = function(view) {
      this.view = view;
      return console.log("set view");
    };

    return loadingController;

  })();
});
