// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["jquery", "application/controllers/baseController"], function($, baseController) {
  var playerController;
  return playerController = (function(_super) {

    __extends(playerController, _super);

    function playerController() {
      return playerController.__super__.constructor.apply(this, arguments);
    }

    return playerController;

  })(baseController);
});
