// Generated by CoffeeScript 1.3.3

define(["jquery"], function($) {
  var Core;
  return Core = (function() {

    function Core() {}

    Core.prototype.init = function() {
      console.log("test");
      return $("body").bind('click', this.dispatch);
    };

    Core.prototype.dispatch = function(event) {
      return console.log(event);
    };

    return Core;

  })();
});
